<a href="https://colab.research.google.com/github/221230045-a11y/221230045-Pengantar-ML/blob/main/Praktikum_2_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Dataset simulasi: 100 samples, 5 features
np.random.seed(42)
X = np.random.randn(100, 5) * 10 + 5  # Mean=5, Std=10

print("Original data shape:", X.shape)


Original data shape: (100, 5)


In [2]:
# SOLUSI TODO 1: Normalisasi Z-score
def z_score_normalization(data):
    mean = np.mean(data, axis=0)
    std = np.std(data, axis=0)
    normalized = (data - mean) / std
    return normalized

X_normalized = z_score_normalization(X)

print("Normalized data mean:", np.mean(X_normalized, axis=0).round(3))
print("Normalized data std:", np.std(X_normalized, axis=0).round(3))


Normalized data mean: [-0.  0. -0. -0.  0.]
Normalized data std: [1. 1. 1. 1. 1.]


In [3]:
# SOLUSI TODO 2: Handle outliers dengan clipping ±3 std
def handle_outliers(data, std_threshold=3):
    mean = np.mean(data, axis=0)
    std = np.std(data, axis=0)

    lower_bound = mean - std_threshold * std
    upper_bound = mean + std_threshold * std

    cleaned = np.clip(data, lower_bound, upper_bound)
    return cleaned

X_cleaned = handle_outliers(X_normalized)

print("Sample cleaned data (first 5 rows):\n", X_cleaned[:5])


Sample cleaned data (first 5 rows):
 [[ 0.604418   -0.21979528  0.75746006  1.461092   -0.18919425]
 [-0.21141045  1.53420502  0.87977344 -0.62585547  0.53845484]
 [-0.46735006 -0.55422449  0.34303561 -2.13809665 -1.58578836]
 [-0.57771567 -1.1129603   0.41687036 -1.08519209 -1.2929218 ]
 [ 1.68601234 -0.30916828  0.16486193 -1.62640854 -0.47982667]]


In [4]:
# SOLUSI TODO 3: One-hot encoding
def one_hot_encoding(labels):
    n_classes = len(np.unique(labels))
    n_samples = len(labels)

    one_hot = np.zeros((n_samples, n_classes))
    for i, label in enumerate(labels):
        one_hot[i, label] = 1
    return one_hot

labels = np.array([0, 1, 2, 0, 1, 2, 0])
one_hot_labels = one_hot_encoding(labels)

print("One-hot labels shape:", one_hot_labels.shape)
print("One-hot labels:\n", one_hot_labels)


One-hot labels shape: (7, 3)
One-hot labels:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [5]:
# SOLUSI TODO 4: Train-test split manual
def train_test_split_numpy(X, y, test_size=0.2):
    n_samples = X.shape[0]
    n_test = int(n_samples * test_size)

    indices = np.random.permutation(n_samples)
    test_indices = indices[:n_test]
    train_indices = indices[n_test:]

    return X[train_indices], X[test_indices], y[train_indices], y[test_indices]

y = np.random.randint(0, 3, 100)  # contoh label
X_train, X_test, y_train, y_test = train_test_split_numpy(X, y, test_size=0.2)

print("Train shape:", X_train.shape, "Test shape:", X_test.shape)


Train shape: (80, 5) Test shape: (20, 5)


In [6]:
# TEST ASSERTIONS
assert X_normalized.shape == X.shape, "Shape should remain same"
assert np.allclose(X_normalized.mean(axis=0), 0, atol=1e-10), "Mean should be ~0 after z-score"
assert np.allclose(X_normalized.std(axis=0), 1, atol=1e-10), "Std should be ~1 after z-score"

print("✅ Semua assertions berhasil! Solusi benar.")


✅ Semua assertions berhasil! Solusi benar.
